### ISSUE TITLE
Step 2, Working offline box

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/grow-a-dragonfly#12]
Hi @libxx1,

Working Offline - the ‘Working offline’ title is repeated again in the expandable box. It’s not a big deal, apart from the font being larger than the project font, so it looks odd. ‘Broadcasting spells’ had the following text: ‘Download the Broadcasting spells starter project and open it using the offline editor. Visit Getting started with Scratch for more information on working offline.’ What’s your preferred style?

**Comment by libxx1** [comment]
Hi @megwangrpf I've removed the duplicate title and updated Broadcasting spells to use this style - a one liner in the project plus a link to the reusable ingredient.
